import AuthProvider from '@/components/auth-provider'
import Nav from '@/components/navbar'
import { Providers } from '@/redux/providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Task Treasure - Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AuthProvider>
         
            <Toaster />
            <Nav />
            <Providers>
            {children}
            </Providers>
            
       
        </AuthProvider>
      </body>
    </html>
  )
}
